"use client";

import { useState, useEffect } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/shared/components/ui/card";
import { Button } from "@/shared/components/ui/button";
import { Copy, Download, CheckCircle2 } from "lucide-react";
import { useToast } from "@/shared/components/ui/use-toast";
import { useKeyboardShortcuts } from "@/hooks/use-keyboard-shortcuts";

interface GoldenPromptOutputProps {
  prompt: string;
  cost?: number;
  modelsUsed?: string[];
}

export function GoldenPromptOutput({
  prompt,
  cost,
  modelsUsed,
}: GoldenPromptOutputProps) {
  const [copied, setCopied] = useState(false);
  const { toast } = useToast();

  // Keyboard shortcut: Cmd/Ctrl+C to copy
  useKeyboardShortcuts([
    {
      key: "c",
      ctrlKey: true,
      metaKey: true,
      action: () => {
        copyToClipboard();
      },
      description: "Copy Golden Prompt",
    },
  ]);

  const copyToClipboard = async () => {
    try {
      await navigator.clipboard.writeText(prompt);
      setCopied(true);
      toast({
        title: "Copied!",
        description: "Golden Prompt copied to clipboard",
      });
      setTimeout(() => setCopied(false), 2000);
    } catch (error) {
      toast({
        title: "Error",
        description: "Failed to copy to clipboard",
        variant: "destructive",
      });
    }
  };

  const exportAsCursorRules = () => {
    const content = `# Cursor Rules
# Generated by Consilium

${prompt}
`;
    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = ".cursorrules";
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);

    toast({
      title: "Exported!",
      description: "Golden Prompt exported as .cursorrules file",
    });
  };

  const exportAsMarkdown = () => {
    const content = `# Golden Prompt

${prompt}

${cost ? `\n**Cost:** $${cost.toFixed(4)}` : ""}
${modelsUsed ? `\n**Models Used:** ${modelsUsed.join(", ")}` : ""}
`;
    const blob = new Blob([content], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "golden-prompt.md";
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);

    toast({
      title: "Exported!",
      description: "Golden Prompt exported as Markdown",
    });
  };

  return (
    <Card>
      <CardHeader>
        <div className="flex items-center justify-between">
          <CardTitle>Golden Prompt</CardTitle>
          <div className="flex gap-2">
            <Button
              variant="outline"
              size="sm"
              onClick={copyToClipboard}
              aria-label="Copy to clipboard"
            >
              {copied ? (
                <CheckCircle2 className="h-4 w-4 text-green-500" />
              ) : (
                <Copy className="h-4 w-4" />
              )}
            </Button>
            <Button
              variant="outline"
              size="sm"
              onClick={exportAsCursorRules}
              aria-label="Export as .cursorrules file"
            >
              <Download className="h-4 w-4 mr-2" />
              .cursorrules
            </Button>
            <Button
              variant="outline"
              size="sm"
              onClick={exportAsMarkdown}
              aria-label="Export as Markdown"
            >
              <Download className="h-4 w-4 mr-2" />
              Markdown
            </Button>
          </div>
        </div>
        {cost && (
          <p className="text-sm text-muted-foreground">
            Cost: ${cost.toFixed(4)} | Models: {modelsUsed?.join(", ") || "N/A"}
          </p>
        )}
      </CardHeader>
      <CardContent>
        <div
          className="bg-muted rounded-lg p-4 font-mono text-sm whitespace-pre-wrap break-words"
          role="textbox"
          aria-label="Golden Prompt content"
        >
          {prompt}
        </div>
      </CardContent>
    </Card>
  );
}

