"use client";

import { useState } from "react";
import {
  Card,
  CardContent,
  CardHeader,
  CardTitle,
} from "@/shared/components/ui/card";
import { Button } from "@/shared/components/ui/button";
import { Copy, Download, CheckCircle2, Sparkles } from "lucide-react";
import { useToast } from "@/shared/components/ui/use-toast";
import { useKeyboardShortcuts } from "@/hooks/use-keyboard-shortcuts";
import { cn } from "@/shared/lib/utils";

interface SynthesisOutputProps {
  prompt: string;
  cost?: number;
  modelsUsed?: string[];
}

export function SynthesisOutput({
  prompt,
  cost,
  modelsUsed,
}: SynthesisOutputProps) {
  const [copied, setCopied] = useState(false);
  const { toast } = useToast();

  useKeyboardShortcuts([
    {
      key: "c",
      ctrlKey: true,
      metaKey: true,
      action: () => {
        copyToClipboard();
      },
      description: "Copy Synthesis",
    },
  ]);

  const copyToClipboard = async () => {
    try {
      await navigator.clipboard.writeText(prompt);
      setCopied(true);
      toast({
        title: "Copied!",
        description: "Synthesis copied to clipboard",
      });
      setTimeout(() => setCopied(false), 2000);
    } catch {
      toast({
        title: "Error",
        description: "Failed to copy to clipboard",
        variant: "destructive",
      });
    }
  };

  const exportAsCursorRules = () => {
    const content = `# Cursor Rules
# Generated by Consilium

${prompt}
`;
    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = ".cursorrules";
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);

    toast({
      title: "Exported!",
      description: "Synthesis exported as .cursorrules file",
    });
  };

  const exportAsMarkdown = () => {
    const content = `# Synthesis

${prompt}

${cost ? `\n**Cost:** $${cost.toFixed(4)}` : ""}
${modelsUsed ? `\n**Models Used:** ${modelsUsed.join(", ")}` : ""}
`;
    const blob = new Blob([content], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "synthesis.md";
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);

    toast({
      title: "Exported!",
      description: "Synthesis exported as Markdown",
    });
  };

  return (
    <Card variant="brand" className="overflow-hidden">
      <CardHeader className="bg-gradient-to-r from-primary/10 via-primary/5 to-transparent border-b border-primary/10">
        <div className="flex items-center justify-between gap-4 flex-wrap">
          <div className="flex items-center gap-2">
            <Sparkles className="h-5 w-5 text-primary shrink-0" aria-hidden />
            <CardTitle className="text-xl">Synthesis</CardTitle>
          </div>
          <div className="flex gap-2 flex-wrap">
            <Button
              variant="outline"
              size="sm"
              onClick={copyToClipboard}
              aria-label="Copy to clipboard"
              className={cn(
                "transition-all duration-200",
                copied && "border-green-500/50 bg-green-500/10",
              )}
            >
              {copied ? (
                <CheckCircle2 className="h-4 w-4 text-green-600 dark:text-green-400" />
              ) : (
                <Copy className="h-4 w-4" />
              )}
            </Button>
            <Button
              variant="outline"
              size="sm"
              onClick={exportAsCursorRules}
              aria-label="Export as .cursorrules file"
            >
              <Download className="h-4 w-4 mr-2" />
              .cursorrules
            </Button>
            <Button
              variant="outline"
              size="sm"
              onClick={exportAsMarkdown}
              aria-label="Export as Markdown"
            >
              <Download className="h-4 w-4 mr-2" />
              Markdown
            </Button>
          </div>
        </div>
        {cost != null && (
          <p className="text-sm text-muted-foreground mt-1">
            Cost: ${cost.toFixed(4)}
            {modelsUsed?.length ? ` · Models: ${modelsUsed.join(", ")}` : ""}
          </p>
        )}
      </CardHeader>
      <CardContent className="pt-4">
        <div
          className="bg-muted/50 rounded-lg p-4 font-mono text-sm whitespace-pre-wrap break-words border border-border/50"
          role="textbox"
          aria-label="Synthesis content"
        >
          {prompt}
        </div>
      </CardContent>
    </Card>
  );
}
